version: 0.2
phases:
  install:
    commands:
#      - apt-get -y update
      - gem install cfn-nag
  build:
    commands:
      - chmod +x src/codebuild/scan_templates/scan.sh
      - /bin/bash src/codebuild/scan_templates/scan.sh
