AWSTemplateFormatVersion: '2010-09-09'
Description: "CodeBuild project to validate CloudFormation templates for Self Service with Service Catalog"
Parameters:
  S3Key:
    Description: Source code zip for DR orchestrator
    Type: String
    Default: dr-orchestrator.zip
  RepoName:
    Description: Name for the code commit repository
    Type: String
    Default: aws-dr-orchestrator
  Tag1:
    Description: Environment
    Type: String
    Default:  Value1
  Tag2:
    Description: Application Name
    Type: String
    Default:  Value2
  Tag3:
    Description: Application Name
    Type: String
    Default:  VAlue3

Resources:
  CodeBuildScanTemplates:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: DrOrchestrator-ScanTemplates
      Description: Validate Cloudformation Templates with cfnnag
      ServiceRole:
        Fn::GetAtt:
          - CodeBuildRole
          - Arn
      Artifacts:
        Type: CODEPIPELINE
      EncryptionKey:
        Fn::ImportValue: "dr-orchestrator-kms-arn"
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: src/codebuild/scan_templates/buildspec.yml
      TimeoutInMinutes: 10
      Tags:
        - Key: Tag1
          Value: !Ref Tag1
        - Key: Tag2
          Value: !Ref Tag3
        - Key: Tag3
          Value: !Ref Tag3

  CodeBuildPackageLambda:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: DrOrchestrator-PackageLambda
      Description: Validate Cloudformation Templates with cfnnag
      ServiceRole:
        Fn::GetAtt:
          - CodeBuildRole
          - Arn
      Artifacts:
        Type: CODEPIPELINE
      EncryptionKey:
        Fn::ImportValue: "dr-orchestrator-kms-arn"
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: src/codebuild/package_functions/buildspec.yml

      TimeoutInMinutes: 10
      Tags:
        - Key: Tag1
          Value: !Ref Tag1
        - Key: Tag2
          Value: !Ref Tag3
        - Key: Tag3
          Value: !Ref Tag3

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      Description: CodePipeline role for static analysis of templates.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildManageS3Artifacts
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource:
                  - Fn::ImportValue: "dr-orchestrator-s3-arn"
                  - Fn::Sub:
                      - "${bucketarn}/*"
                      - bucketarn:
                          Fn::ImportValue: "dr-orchestrator-s3-arn"
                  - arn:aws:s3:::taskcat-*
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                  - logs:CreateLogGroup
                Resource:
                  - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
              - Action:
                  - 'kms:Encrypt'
                  - 'kms:Decrypt'
                  - 'kms:ReEncrypt*'
                  - 'kms:GenerateDataKey*'
                  - 'kms:DescribeKey'
                Resource:
                  Fn::ImportValue: "dr-orchestrator-kms-arn"
                Effect: Allow

              - Action:
                  - "ssm:GetParameters"
                Resource: "*"
                Effect: Allow
      Tags:
        - Key: Tag1
          Value: !Ref Tag1
        - Key: Tag2
          Value: !Ref Tag3
        - Key: Tag3
          Value: !Ref Tag3

  SSMParameterCodeBuildScanStage:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "DR Orchestrator codebuild stage - scan templates"
      Name: "/drorchestrator/baseline/codebuild-scan-templates"
      Type: String
      Value: !Ref CodeBuildScanTemplates
      Tags:
        Tag1: !Ref Tag1
        Tag2: !Ref Tag2
        Tag3: !Ref Tag3

  SSMParameterCodeBuildLambdaPackageStage:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "DR Orchestrator codebuild stage - lambda package"
      Name: "/drorchestrator/baseline/cocdebuild-package-lambda"
      Type: String
      Value: !Ref CodeBuildPackageLambda
      Tags:
        Tag1: !Ref Tag1
        Tag2: !Ref Tag2
        Tag3: !Ref Tag3

  SSMParameterCodeBuildRole:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "DR Orchestratorsolution bucket shared with AWS Organization"
      Name: "/drorchestrator/baseline/codebuild-rolename"
      Type: String
      Value: !Ref CodeBuildRole
      Tags:
        Tag1: !Ref Tag1
        Tag2: !Ref Tag2
        Tag3: !Ref Tag3

  SSMParameterCodeBuildStackName:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "DR Orchestrator codebuild stage - lambda package"
      Name: "/drorchestrator/baseline/codebuild-stackname"
      Type: String
      Value: !Ref AWS::StackName
      Tags:
        Tag1: !Ref Tag1
        Tag2: !Ref Tag2
        Tag3: !Ref Tag3

